# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: node:16-bullseye
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    strategy:
      matrix:
        node: [16, 17]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache
        uses: actions/cache@v2
        id: cache-lerna
        env:
          cache-name: cache-lerna
        with:
          path: |
            node_modules
            package-lock.json
            packages/*/.eslintcache
            packages/*/.vscode
            packages/*/dist
            packages/*/node_modules
            packages/*/package-lock.json
          key: ${{ runner.OS }}-build-${{ env.cache-name }}-${{ github.ref }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-${{ github.ref }}-

      - name: Prepare
        run: |
          uname -a
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq --yes > /dev/null
          apt-get upgrade -qq --yes > /dev/null
          apt-get install -qq --yes --no-install-recommends bash dnsutils git jq locales net-tools wget > /dev/null
          apt-get install -qq --yes postgresql-client > /dev/null
          uname -a
          npm -v && node -v
          git --version
          openssl version
          cat /etc/*release
          sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen
          locale-gen
          locale -a

      - name: Build
        run: |
          whoami
          export cwd=`pwd`
          . .scripts/ci/ci-env.sh
          sh .scripts/ci/ci-prepare.sh
          sh .github/workflows/fix.sh
          npm i -g c8 rollup standard-version
          sh .github/workflows/fix.sh
          npm i
          sh .github/workflows/fix.sh
          npm run build --if-present
        env:
          CI: true

      - name: Lint
        run: |
          export cwd=`pwd`
          . .scripts/ci/ci-env.sh
          sh .scripts/ci/ci-prepare.sh
          npm run lint:nofix
        env:
          CI: true

      - name: Testing
        run: |
          export cwd=`pwd`
          . .scripts/ci/ci-env.sh
          sh .scripts/ci/ci-prepare.sh
          npm run cov
        env:
          CI: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

